import { ArrowUpRightIcon, ArrowRightIcon } from "@/components/icons";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { MediaFrame } from "@/components/media-frame";
import { media } from "@/data/site";

export const metadata: Metadata = { title: "Engineering", description: "A concept approach to integrated automotive performance engineering." };
const stages = [
  { name: "Assessment", text: "Understand the vehicle, its intended use and what the driver wants to feel. Establish the mechanical and aesthetic constraints." },
  { name: "Specification", text: "Select powertrain, chassis and body changes as a system. Define a clear purpose for every proposed part." },
  { name: "Integration", text: "Resolve packaging, clearances, heat, finish and service access before calling the design complete." },
  { name: "Validation", text: "In a real commission, test behavior across road, thermal and durability conditions. This concept does not claim physical validation." },
];

export default function EngineeringPage() { return <div className="page-shell engineering-page"><header className="page-intro section-pad"><p className="eyebrow">ENGINEERING / THE CONNECTED CAR</p><h1>Systems first.<br /><em>Numbers second.</em></h1><div className="page-intro-bottom"><p>Power is only compelling when the car can manage it. The best work makes the complex feel natural.</p><span className="mono">ASSESS <ArrowRightIcon /> SPECIFY <ArrowRightIcon /> INTEGRATE <ArrowRightIcon /> VALIDATE</span></div></header><section className="engineering-lead section-pad"><MediaFrame media={media.v01Engine} sizes="100vw" /><div className="engineering-lead-copy"><p className="eyebrow">INTEGRATION / V01 STUDY</p><h2>No isolated upgrades.</h2><p>Cooling shapes the front end. Tire choice changes steering. Exhaust routing changes heat management and sound. The build succeeds when those decisions reinforce one another.</p></div></section><section className="engineering-process section-pad"><p className="eyebrow">THE PROCESS / FOUR STAGES</p><div>{stages.map((stage, index) => <article key={stage.name}><span className="mono">0{index + 1}</span><h2>{stage.name}</h2><p>{stage.text}</p></article>)}</div></section><section className="engineering-diagram section-pad"><div><p className="eyebrow">SCHEMATIC / SYSTEM MAP</p><h2>Cause and effect,<br /><em>made visible.</em></h2><p>This illustrative diagram communicates the relationship between four domains. It is a concept explanation, not a production drawing or validated design.</p></div><div><Image src="/diagrams/vehicle-systems.svg" width={940} height={480} alt="Side-view schematic connecting powertrain, aero, cabin and chassis elements" /><span className="mono">SCHEMATIC CONCEPT / NOT AN ENGINEERING DRAWING</span></div></section><section className="engineering-material section-pad"><MediaFrame media={media.exhaust} sizes="(max-width: 800px) 100vw, 55vw" /><div><p className="eyebrow">MATERIAL / FABRICATION</p><h2>The finish<br />follows the fit.</h2><p>Material choice affects mass, sound, thermal behavior and longevity. Visual quality begins with decisions that are invisible in the finished car.</p><Link className="text-link" href="/enquiry?service=exhaust">Discuss an upgrade <span className="action-icon" aria-hidden><ArrowUpRightIcon /></span></Link></div></section></div>; }
